name: Release Final Product

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prep Misc Env Vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Build Fat JAR
        run: |
          chmod +x ./mvnw
          ./mvnw clean
          ./mvnw com.googlecode.maven-download-plugin:download-maven-plugin:wget@install-arduino-libs
          ./mvnw package

      - name: Create release ZIP
        run: |
          mkdir -p ./Drizzle/tool
          mv ./target/*.jar ./Drizzle/tool
          cp README.md ./Drizzle
          cp LICENSE ./Drizzle
          zip -9r drizzle.zip ./Drizzle
          rm -fr ./Drizzle

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Drizzle ${{ github.ref }}
          body: To install Drizzle ${{ steps.vars.outputs.tag }} unzip it inside Arduino IDE's installation directory / tools
          draft: false
          prerelease: false

      - name: Add archive asset to the release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: drizzle.zip
          asset_name: drizzle-${{ steps.vars.outputs.tag }}-dist.zip
          asset_content_type: application/zip