name: Release Final Product

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prep Misc Env Vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Build Distribution JAR
        run: |
          chmod +x ./mvnw
          ./mvnw clean
          ./mvnw com.googlecode.maven-download-plugin:download-maven-plugin:wget@install-arduino-libs
          ./mvnw package

      - name: Create release ZIP
        run: |
          mkdir -p ./Drizzle/tool
          mv ./target/*-with-deps.jar ./Drizzle/tool
          cp README.md ./Drizzle
          cp LICENSE ./Drizzle
          zip -9r drizzle-${{ steps.vars.outputs.tag }}-dist.zip ./Drizzle
          rm -fr ./Drizzle

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" -t "Drizzle ${{ github.ref_name }}" --generate-notes drizzle-${{ steps.vars.outputs.tag }}-dist.zip
          echo -e "To install Drizzle ${{ steps.vars.outputs.tag }} unzip it inside Arduino IDE's installation directory / tools\nIf you have a previous version already installed remove it from the tools directory.\n\n" >release_notes.txt
          gh release view "${{ github.ref_name }}" -t {{.body}} --json body >>release_notes.txt
          gh release edit "${{ github.ref_name }}" -F release_notes.txt
          rm release_notes.txt